# Generated by Django 4.1.4 on 2023-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
