# Generated by Django 4.1.4 on 2023-01-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everestapp', '0002_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='deleted_at',
        ),
    ]
